[package]
name = "unitodo"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
home = "0.5" # For finding the home directory
clap = { version = "4.4", features = ["derive"] } # Added clap dependency 