output_file = "/Users/asc/Documents/Obsidian/alpha-vault/Life/unitodo.sync.md"

[ag]
pattern = "TODO|- \\[ \\]"

# Paths to search for TODOs (defaults to [\".\"] if empty or not present)
paths = ["/Users/asc/repo", "/Users/asc/Documents/Obsidian/alpha-vault"] # Example path, adjust as needed

# Patterns/directories to ignore (uses ag's --ignore flag)
ignore = [
    ".git",
    "target",
    "node_modules",
    "build",
    "dist",
    # mine:
    "_cloned_", # Relative path
    "_study_", # Relative path
    "tmp", # Relative path
    "_archive_", # Relative path
    "unitodo.sync.md",
    "*.temp.*",
]


[projects]
# project_name = "regex_of_relative_path"

Unitodo = ".*/Unitodo.*"
Ceal = ".*/Ceal.*"