[rg]
pattern = "TODO:|TODO|- \\[ \\] "
# Paths to search for TODOs (defaults to ["."] if empty or not present)
paths = ["/Users/asc/repo", "/Users/asc/Documents/Obsidian/alpha-vault"] # Example path, adjust as needed
# Patterns/directories to ignore (supplements rg's ignore mechanism)
ignore = [
    ".git",
    "target",
    "node_modules",
    "build",
    "dist",
    # mine:
    "*.toml",
    "/Users/asc/repo/_cloned_/**", # Relative path
    "/Users/asc/repo/_study_/**", # Relative path
    "/Users/asc/repo/tmp/**", # Relative path
    "/Users/asc/repo/_archive_/**", # Relative path
    "*/unitodo.sync.*",
    "*.temp.*",
    "/Users/asc/repo/Unitodo/README.md",
]

[projects]
# project_name = ["glob_pattern_1", "glob_pattern_2"]
Unitodo = ["**/Unitodo.md", "**/Unitodo/**"] # Example: Match any path containing Unitodo
Ceal = ["**/Ceal.*", "**/Ceal/**"]       # Example: Match any path containing Ceal
# Add more projects and their glob patterns here