# output_file = "/Users/asc/Documents/Obsidian/alpha-vault/Life/unitodo.sync.md"
output_file = "unitodo.sync.md"

[ag]
pattern = "TODO|- \\[ \\]"

# Paths to search for TODOs (defaults to [\".\"] if empty or not present)
paths = ["/Users/asc/repo", "/Users/asc/Documents/Obsidian/alpha-vault"] # Example path, adjust as needed

# Patterns/directories to ignore (uses ag's --ignore flag)
ignore = [
    ".git",
    "target",
    "node_modules",
    "build",
    "dist",
    "*.toml",
    # mine:
    "_cloned_", # Relative path
    "_study_", # Relative path
    "tmp", # Relative path
    "_archive_", # Relative path
    "unitodo.sync.md",
    "*.temp.*",
]


[projects]
# project_name = ["glob_pattern_1", "glob_pattern_2"]

Unitodo = ["**/Unitodo.md", "**/Unitodo/**"] # Example: Match any path containing Unitodo
Ceal = ["**/Ceal.*", "**/Ceal/**"]       # Example: Match any path containing Ceal
# Add more projects and their glob patterns here